### PR TITLE
Cleanup VM in case of a failure

### LINKED ISSUE #115: No cleanup after failure & ctrl-c stops the VM
Two behavioral issues here: No cleanup after failure and Ctrl-C stops the VM:

1. When the packer is failed to build the VM (`macos1306` in this case) - it leaves the image in local registry:
   ```
   ...
   Cancelling build after receiving interrupt
   2024/02/29 12:41:53 Cancelling builder after context cancellation context canceled
   2024/02/29 12:41:53 packer-plugin-ansible_v1.1.1_x5.0_darwin_arm64 plugin: 2024/02/29 12:41:53 Received interrupt signal (count: 1). Ignoring.
   2024/02/29 12:41:53 packer-provisioner-shell plugin: Received interrupt signal (count: 1). Ignoring.
   2024/02/29 12:41:53 packer-plugin-tart_v1.8.1_x5.0_darwin_arm64 plugin: 2024/02/29 12:41:53 Received interrupt signal (count: 1). Ignoring.
   ==> tart-cli: Failed to run the boot command: context canceled
   ==> tart-cli: Failed to run the boot command: context canceled
   ==> tart-cli: Step "stepRun" failed
   ==> tart-cli: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c
   ==> tart-cli: Waiting for the tart process to exit...
   ==> tart-cli: Connection reset by peer (os error 54)
   ==> Wait completed after 4 minutes 34 seconds
   Build 'tart-cli' errored after 4 minutes 34 seconds: Failed to run the boot command: context canceled
   
   ==> Wait completed after 4 minutes 34 seconds
   2024/02/29 12:42:10 waiting for all plugin processes to complete...
   Cleanly cancelled builds after being interrupted.
   2024/02/29 12:42:10 /Users/admin/.config/packer/plugins/github.com/cirruslabs/tart/packer-plugin-tart_v1.8.1_x5.0_darwin_arm64: plugin process exited
   2024/02/29 12:42:10 /Users/admin/git/aquarium-bait/.bin/packer: plugin process exited
   2024/02/29 12:42:10 /Users/admin/.config/packer/plugins/github.com/hashicorp/ansible/packer-plugin-ansible_v1.1.1_x5.0_darwin_arm64: plugin process exited
   ...
   $ tart list
   Source Name      Size State  
   local  macos1306 15   stopped
   local  test1     23   stopped
   ...
   ```
   Usually build plugins cleans up after that - so maybe there is some sort of issue in the cleanup logic?

2. Ctrl-C during packer execution for some reason stops the VM. Should not happen - VM need to be stopped only in cleanup stage when user decided to cleanup the environment.

### PR DESCRIPTION
**Pull request by fkorotkov**
Fixes #115

### CODE REVIEW

**Comment by fkorotkov** [comment]
@sparshev FYI

**Comment by sparshev** [comment]
Sorrying just one file is changed, while we have 3 separated steps for this matter:
* step_clone_vm.go
* step_create_linux_vm.go
* step_create_vm.go

But I'm not sure I really understand the codebase, so could be wrong.

**Comment by fkorotkov** [comment]
Good catch, @sparshev! I've extracted cleanup in a separate step which is the first one. `Cleanup` functions are called in reverse order so it will be called the last.

**Comment by sparshev** [comment]
Yep, now looks better!) Do you think this PR will contain a fix for Ctrl-C issue as well, because in description it says `Fixes #115`. Or I can create a separated issue about Ctrl-C.

**Comment by fkorotkov** [comment]
It seems it will be handled according to [Packer documentation](https://developer.hashicorp.com/packer/docs/plugins/creation/custom-builders#context-cancellation-from-packer-v1-4):

> Cancels are most commonly triggered by external interrupts, such as the user pressing `Ctrl-C`. Packer will only exit once all the builders clean up...

**Comment by sparshev** [comment]
Unfortunately this is not the issue - the issue with Ctrl-C that Tart VM is going down immediately after Ctrl-C, not after cleanup operation... So when you press Ctrl-C in packer with `--on-error=ask` the VM should continue to live until `c` and `enter` were pressed.

**Comment by fkorotkov** [comment]
Oh. I think I misunderstood you but I still think that `Ctrl+C` will be handled since `shutdown -h now` is send in `Cleanup` of a run step. 

@edigaryev is on PTO so I'm going to merge now so we can do a release. He'll review the change post-factum.

**Comment by torarnv** [comment]
Does this take the `packer build -on-error=` argument into account?

`-on-error=[cleanup|abort|ask|run-cleanup-provisioner] If the build fails do: clean up (default), abort, ask, or run-cleanup-provisioner.`

If I pass `ask` and press Ctrl+C, the VM is still deleted. I would have expected it to stay around, so I could debug what went wrong.

It seems to work fine if the cancellation is coming from a step, e.g. if the SSH times out. In that case the cleanup is not run when I choose so via the `ask` menu.

**Comment by torarnv** [comment]
"Internal" failure. Choice respected:

``` 
==> macos.tart-cli.install-os: Creating virtual machine...
    macos.tart-cli.install-os: Installing OS...
    macos.tart-cli.install-os: 0%
    macos.tart-cli.install-os: Error: An error occurred during installation. Installation failed.
==> macos.tart-cli.install-os: Failed to create a VM: Bad exit status: 1
==> macos.tart-cli.install-os: Step "stepCreateVM" failed
==> macos.tart-cli.install-os: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? a
==> macos.tart-cli.install-os: Failed to create a VM: Bad exit status: 1
==> macos.tart-cli.install-os: Step "stepCreateVM" failed, aborting...
==> macos.tart-cli.install-os: aborted: skipping cleanup of step "stepCleanVM"
Build 'macos.tart-cli.install-os' errored after 2 minutes 10 seconds: Failed to create a VM: Bad exit status: 1
```

Ctrl+C. Choice ignored:
``` 
==> macos.tart-cli.install-os: Creating virtual machine...
    macos.tart-cli.install-os: Installing OS...
    macos.tart-cli.install-os: 0%
Cancelling build after receiving interrupt
==> macos.tart-cli.install-os: Failed to create a VM: Bad exit status: -1
==> macos.tart-cli.install-os: Step "stepCreateVM" failed
==> macos.tart-cli.install-os: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? a
==> macos.tart-cli.install-os: Cleaning up virtual machine...
    macos.tart-cli.install-os: failed to open lock file file:///Users/torarne/.tart/vms/macos-preinstall:13.6.0+22G120/config.json: No such file or directory
Build 'macos.tart-cli.install-os' errored after 1 second 874 milliseconds: Failed to create a VM: Bad exit status: -1
```

**Comment by torarnv** [comment]
Awesome @edigaryev !

**Pull request merged**
